spring:
  application:
    name: crewsec-backend

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/crewsec?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=False
    username: root
    password: Abde@2001

storage:
  location: /Users/blanzin/Desktop/bucket

server:
  port: 5000


token:
  signing:
    key: phdin9WOVV3EJZdJyVvxeXeG3ieE5IH/WlyQBGC7uGk=