spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crewsec?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=False
    username: root
    password: Abde@2001

token:
  signing:
    key: ZpgvK69ofziH64hPyJuysTEmixjVXn7byP1YISwmeSbYiCElZ39E/g==